//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumeBuild {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YumeBuild.DefaultRes", typeof(DefaultRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///  &lt;RebuildConfig&gt;
        ///    &lt;Paths&gt;
        ///      &lt;Content&gt;&lt;/Content&gt;
        ///      &lt;Winget&gt;0&lt;/Winget&gt;
        ///      &lt;Database&gt;&lt;/Database&gt;
        ///      &lt;Script&gt;&lt;/Script&gt;
        ///    &lt;/Paths&gt;
        ///  &lt;/RebuildConfig&gt;
        ///			.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///	&lt;Database&gt;
        ///		&lt;Application&gt;
        ///      &lt;ID&gt;0&lt;/ID&gt;
        ///			&lt;Name&gt;Example Name&lt;/Name&gt;
        ///			&lt;Desc&gt;Test Example App&lt;/Desc&gt;
        ///			&lt;PathName&gt;Example&lt;/PathName&gt;
        ///			&lt;MSI&gt;N&lt;/MSI&gt;
        ///			&lt;CMD&gt;N&lt;/CMD&gt;
        ///      &lt;Winget&gt;N&lt;/Winget&gt;
        ///      &lt;WingetName&gt;Test.App&lt;/WingetName&gt;
        ///			&lt;Info&gt;Test Data&lt;/Info&gt;
        ///		&lt;/Application&gt;
        ///	&lt;/Database&gt;
        ///			.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UsersManual {
            get {
                object obj = ResourceManager.GetObject("UsersManual", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
